config/routes.rb
Rails.application.routes.draw do
  resources :houses
  resources :people
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/house.rb
class House < ActiveRecord::Base
  # has_many :people, dependent: :destroy
  # validates :name, presence: true
  # validates :motto, presence: true
  # validates :img_url, presence: true
  # validates :region, presence: true
  # validates :seat, presence: true
  # validates :seat_img, presence: true
end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :house
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController

    def index
      @houses = House.all
    end

    def show
      @house = House.find(params[:id])
    end

    def new
      @house = House.new
    end

    def create
      @house = House.create(house_params)
      if @house.save
      redirect_to @house, notice: @house.name + " was successfully created."
    else
      render :new
    end
    end

    def edit
      @house = House.find(params[:id])
    end

    def update
      @house = House.find(params[:id])
      @house.update(house_params)
      redirect_to @house
    end

    def destroy
      @house = House.find(params[:id])
      @house.destroy
      redirect_to houses_path
    end

    private
    def house_params
      params.require(:house).permit(:name, :img_url, :motto)
    end
  end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def index
    @persons = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.create!(person_params)
    redirect_to @person
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    @person.update(person_params)
    redirect_to @person
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to people_path
  end

  private
  def person_params
    params.require(:person).permit(:name, :img_url, :motto, :house_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/houses/_form.html.erb
<div class="form">
<% @house.errors.full_messages.each do |message| %>
<p>
  <%= message %>
</p>
<% end %>

<%= form_for @house do |f| %>
<h2>Create New House</h2>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :img_url %>
  <%= f.text_field :img_url %>

  <%= f.label :motto %>
  <%= f.text_field :motto %>

  <%= f.submit %>
<% end %>
</div>

app/views/houses/_house.html.erb
<li>
    <%= link_to house.name, house %> | <%= link_to 'Delete', house_path(house),
                                            method: :delete,
                                            data: { confirm: 'Are you sure?' } %>
</li>

app/views/houses/edit.html.erb
<h2>Edit <%= @house.name %></h2>
<%= link_to 'Delete', house_path(@house),
                                        method: :delete,
                                        data: { confirm: 'Are you sure?' } %>

<%= render 'form' %>

app/views/houses/index.html.erb
<div class="whitespace"></div>
<div id="houses" class="transitions-enabled">
  <% @houses.each do |house| %>
  <div class="box">
    <%= link_to image_tag("#{house.img_url}"), house_path(house) %>
  </div>
    <% end %>
</div>

app/views/houses/new.html.erb
<div class="whitespace"></div>


<%= render 'form' %>

app/views/houses/show.html.erb
<% flash.each do |type, message| %>
  <p><%= type %>: <%= message %></p>
<% end %>
<div class="whitespace"></div>
<div class="house-profile">
<h2>
  <%= @house.name %>
  <h2>
  <h3><%= link_to "Edit", edit_house_path(@house) %>
  <%= link_to "Delete", house_path(@house),
                                        method: :delete,
                                        data: { confirm: 'Are you sure?' } %></h3>

<hr>
<div class="houses">
<img class="sigil" src="<%= @house.img_url %>">
</div>
</p>House Words:</p><h4><%= @house.motto %></h4>
<p>Seat of Power:</p><h4><%= @house.seat %></h4>
<div>
<img src="<%= @house.seat_img %>">
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GOT2</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header>
    <h1>Game of Thrones</h1>
<nav>
  <ul>
  <li><%= link_to "Houses", houses_path(@house) %> </li>
  <li><%= link_to "Characters", people_path(@person) %></li>
  <li><%= link_to "New House", new_house_path %></li>
  <li><%= link_to "Add Character (+)", new_person_path %></li>
  </ul>
</nav>
</header>

  <%= yield %>
</body>
</html>

app/views/people/_form.html.erb
<div class="form">
<%= form_for @person do |f| %>
<h2>Create New Character</h2>
  <%= f.label :name %>
  <%= f.text_field :name %>



  <%= f.select( :house_id, House.all.collect { |house| [house.name, house.id] } ) %>

  <%= f.label :img_url %>
  <%= f.text_field :img_url %>


  <%= f.submit %>
<% end %>
</div>

app/views/people/edit.html.erb
<h2>Edit <%= @person.name %></h2>
<%= link_to 'Delete', person_path(@person),
                                              method: :delete,
                                              data: { confirm: 'Are you sure?' } %>



<%= render 'form'  %>

app/views/people/index.html.erb
<div class="whitespace"></div>
<div id="people" class="transitions-enabled">
  <% @persons.each do |person| %>
  <div class="box">
<%= link_to image_tag("#{person.img_url}"), person_path(person) %>
</div>
  <% end %>
</div>

app/views/people/new.html.erb
<div class="whitespace"></div>

<%= render 'form'  %>

app/views/people/show.html.erb
<% flash.each do |type, message| %>
  <p><%= type %>: <%= message %></p>
<% end %>

<div class="whitespace"></div>
<div class="person-profile">
<h1>Name: <%= @person.name %></h1>
<h3>
  <%= link_to "(edit)", edit_person_path(@person) %> |
  <%= link_to 'Delete', person_path(@person),
                                                method: :delete,
                                                data: { confirm: 'Are you sure?' } %>
</h3>
<hr>
<img src="<%= @person.img_url %>">


<h2>House: <%= @person.house_id %></h2>
<h2>Biograhpy:</h2>
</div>